import type { Account, Category } from '../types/models';

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc-cash-default',
    name: 'Efectivo',
    type: 'CASH',
    initialBalance: 0,
    color: '#10b981',
    icon: 'Banknote',
    isArchived: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'acc-debit-default',
    name: 'Cuenta Débito Principal',
    type: 'DEBIT',
    initialBalance: 0,
    color: '#3b82f6',
    icon: 'CreditCard',
    isArchived: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  // Gastos Principales
  {
    id: 'cat-renta',
    name: 'Renta',
    parentId: null,
    type: 'EXPENSE',
    icon: 'Home',
    color: '#ef4444',
    isDefault: true,
    isArchived: false,
  },
  {
    id: 'cat-comida',
    name: 'Comida',
    parentId: null,
    type: 'EXPENSE',
    icon: 'Utensils',
    color: '#f97316',
    isDefault: true,
    isArchived: false,
  },
  {
    id: 'cat-comida-super',
    name: 'Supermercado',
    parentId: 'cat-comida',
    type: 'EXPENSE',
    icon: 'ShoppingCart',
    color: '#f97316',
    isDefault: true,
    isArchived: false,
  },
  {
    id: 'cat-comida-restaurantes',
    name: 'Restaurantes',
    parentId: 'cat-comida',
    type: 'EXPENSE',
    icon: 'Coffee',
    color: '#f97316',
    isDefault: true,
    isArchived: false,
  },
  {
    id: 'cat-transporte',
    name: 'Transporte',
    parentId: null,
    type: 'EXPENSE',
    icon: 'Car',
    color: '#eab308',
    isDefault: true,
    isArchived: false,
  },
  {
    id: 'cat-transporte-gas',
    name: 'Gasolina',
    parentId: 'cat-transporte',
    type: 'EXPENSE',
    icon: 'Fuel',
    color: '#eab308',
    isDefault: true,
    isArchived: false,
  },
  {
    id: 'cat-transporte-publico',
    name: 'Transporte Público',
    parentId: 'cat-transporte',
    type: 'EXPENSE',
    icon: 'Bus',
    color: '#eab308',
    isDefault: true,
    isArchived: false,
  },
  {
    id: 'cat-servicios',
    name: 'Servicios',
    parentId: null,
    type: 'EXPENSE',
    icon: 'Zap',
    color: '#06b6d4',
    isDefault: true,
    isArchived: false,
  },
  {
    id: 'cat-servicios-luz',
    name: 'Electricidad / Agua',
    parentId: 'cat-servicios',
    type: 'EXPENSE',
    icon: 'Droplet',
    color: '#06b6d4',
    isDefault: true,
    isArchived: false,
  },
  {
    id: 'cat-servicios-internet',
    name: 'Internet y Telefonía',
    parentId: 'cat-servicios',
    type: 'EXPENSE',
    icon: 'Wifi',
    color: '#06b6d4',
    isDefault: true,
    isArchived: false,
  },
  {
    id: 'cat-entretenimiento',
    name: 'Entretenimiento',
    parentId: null,
    type: 'EXPENSE',
    icon: 'Film',
    color: '#8b5cf6',
    isDefault: true,
    isArchived: false,
  },
  {
    id: 'cat-entretenimiento-streaming',
    name: 'Streaming y Juegos',
    parentId: 'cat-entretenimiento',
    type: 'EXPENSE',
    icon: 'Tv',
    color: '#8b5cf6',
    isDefault: true,
    isArchived: false,
  },
  {
    id: 'cat-salud',
    name: 'Salud',
    parentId: null,
    type: 'EXPENSE',
    icon: 'HeartPulse',
    color: '#ec4899',
    isDefault: true,
    isArchived: false,
  },
  {
    id: 'cat-salud-farmacia',
    name: 'Farmacia y Medicamentos',
    parentId: 'cat-salud',
    type: 'EXPENSE',
    icon: 'Pill',
    color: '#ec4899',
    isDefault: true,
    isArchived: false,
  },
  {
    id: 'cat-otros',
    name: 'Otros',
    parentId: null,
    type: 'EXPENSE',
    icon: 'MoreHorizontal',
    color: '#64748b',
    isDefault: true,
    isArchived: false,
  },
  // Ingresos
  {
    id: 'cat-ingreso-nomina',
    name: 'Nómina / Salario',
    parentId: null,
    type: 'INCOME',
    icon: 'Briefcase',
    color: '#10b981',
    isDefault: true,
    isArchived: false,
  },
  {
    id: 'cat-ingreso-ventas',
    name: 'Ventas y Negocio',
    parentId: null,
    type: 'INCOME',
    icon: 'TrendingUp',
    color: '#14b8a6',
    isDefault: true,
    isArchived: false,
  },
  {
    id: 'cat-ingreso-otros',
    name: 'Otros Ingresos',
    parentId: null,
    type: 'INCOME',
    icon: 'PlusCircle',
    color: '#22c55e',
    isDefault: true,
    isArchived: false,
  },
];
